version: '3'
services:
#####
  myapp_practica:
    # context: .
    build: .
    container_name: myapp_practica
    ports:
      - "83:3000"
    networks:
    - network_practica
#####
  prometeus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    networks:
    - network_practica
    ports:
      - "9090:9090"
    depends_on: 
      - myapp_practica
    restart: on-failure
#####
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM= true"
      - "GF_AUTH_ANONYMOUS_ENABLED= true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE= Admin"
      - "GF_INSTALL_PLUGINS=grafana-clock-panel"
    networks:
      - network_practica
    volumes:
      - myGrafanaVol:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3500:3000"
    depends_on: 
     - prometeus
    links:
     - prometeus
volumes:
  prometheus.yml:
  myGrafanaVol:

networks:
  network_practica: